SELECT
    KC.CONTENT || SE.RACE_BANGO || 'R ' || strftime('%H:%M', RA.HASSO_JIKOKU)
    , SE.WAKUBAN || '枠' || SE.UMABAN || '番' AS WAKUBAN
    , SE.BAMEI AS BAMEI
    , SC.CONTENT || SE.BAREI AS SEIREI
    , SE.FUTAN_JURYO AS KINRYO
    , UM.BAMEI_EUR || ' / ' || SE.KETTO_TOROKU_BANGO AS ENG_NAME
    , '総合成績 ' || UM1.SOGO_1CHAKU || ' - ' || UM1.SOGO_2CHAKU || ' - ' || UM1.SOGO_3CHAKU || ' - ' ||
    (UM1.SOGO_4CHAKU + UM1.SOGO_5CHAKU + UM1.SOGO_CHAKUGAI) AS SOGO_SEISEKI
    , '芝 ' || (UM1.SHIBA_RYO_1CHAKU + UM1.SHIBA_YAYAOMO_1CHAKU + UM1.SHIBA_OMO_1CHAKU + UM1.SHIBA_FURYO_1CHAKU) ||
    ' - ' || (UM1.SHIBA_RYO_2CHAKU + UM1.SHIBA_YAYAOMO_2CHAKU + UM1.SHIBA_OMO_2CHAKU + UM1.SHIBA_FURYO_2CHAKU) ||
    ' - ' || (UM1.SHIBA_RYO_3CHAKU + UM1.SHIBA_YAYAOMO_3CHAKU + UM1.SHIBA_OMO_3CHAKU + UM1.SHIBA_FURYO_3CHAKU) ||
    ' - ' || (UM1.SHIBA_RYO_4CHAKU + UM1.SHIBA_YAYAOMO_4CHAKU + UM1.SHIBA_OMO_4CHAKU + UM1.SHIBA_FURYO_4CHAKU + 
	UM1.SHIBA_RYO_5CHAKU + UM1.SHIBA_YAYAOMO_5CHAKU + UM1.SHIBA_OMO_5CHAKU + UM1.SHIBA_FURYO_5CHAKU +
	UM1.SHIBA_RYO_CHAKUGAI + UM1.SHIBA_YAYAOMO_CHAKUGAI + UM1.SHIBA_OMO_CHAKUGAI + UM1.SHIBA_FURYO_CHAKUGAI)
    AS TURF
    , '芝重不 ' || (UM1.SHIBA_OMO_1CHAKU + UM1.SHIBA_FURYO_1CHAKU) ||
    ' - ' || (UM1.SHIBA_OMO_2CHAKU + UM1.SHIBA_FURYO_2CHAKU) ||
    ' - ' || (UM1.SHIBA_OMO_3CHAKU + UM1.SHIBA_FURYO_3CHAKU) ||
    ' - ' || (UM1.SHIBA_OMO_4CHAKU + UM1.SHIBA_FURYO_4CHAKU + 
	UM1.SHIBA_OMO_5CHAKU + UM1.SHIBA_FURYO_5CHAKU +
	UM1.SHIBA_OMO_CHAKUGAI + UM1.SHIBA_FURYO_CHAKUGAI)
    AS TURF_OMO_FURYO
    , '中央平地 ' || (UM1.CHUO_GOKEI_1CHAKU - UM1.SHOGAI_1CHAKU) ||
    ' - ' || (UM1.CHUO_GOKEI_2CHAKU - UM1.SHOGAI_2CHAKU) ||
    ' - ' || (UM1.CHUO_GOKEI_3CHAKU - UM1.SHOGAI_3CHAKU) ||
    ' - ' || (UM1.CHUO_GOKEI_4CHAKU - UM1.SHOGAI_4CHAKU +
	UM1.CHUO_GOKEI_5CHAKU - UM1.SHOGAI_5CHAKU +
	UM1.CHUO_GOKEI_CHAKUGAI - UM1.SHOGAI_CHAKUGAI) AS CHUO_HEICHI
    , 'ダ ' || (UM1.DIRT_RYO_1CHAKU + UM1.DIRT_YAYAOMO_1CHAKU + UM1.DIRT_OMO_1CHAKU + UM1.DIRT_FURYO_1CHAKU) ||
    ' - ' || (UM1.DIRT_RYO_2CHAKU + UM1.DIRT_YAYAOMO_2CHAKU + UM1.DIRT_OMO_2CHAKU + UM1.DIRT_FURYO_2CHAKU) ||
    ' - ' || (UM1.DIRT_RYO_3CHAKU + UM1.DIRT_YAYAOMO_3CHAKU + UM1.DIRT_OMO_3CHAKU + UM1.DIRT_FURYO_3CHAKU) ||
    ' - ' || (UM1.DIRT_RYO_4CHAKU + UM1.DIRT_YAYAOMO_4CHAKU + UM1.DIRT_OMO_4CHAKU + UM1.DIRT_FURYO_4CHAKU + 
	UM1.DIRT_RYO_5CHAKU + UM1.DIRT_YAYAOMO_5CHAKU + UM1.DIRT_OMO_5CHAKU + UM1.DIRT_FURYO_5CHAKU +
	UM1.DIRT_RYO_CHAKUGAI + UM1.DIRT_YAYAOMO_CHAKUGAI + UM1.DIRT_OMO_CHAKUGAI + UM1.DIRT_FURYO_CHAKUGAI)
    AS DIRT
    , 'ダ重不 ' || (UM1.DIRT_OMO_1CHAKU + UM1.DIRT_FURYO_1CHAKU) ||
    ' - ' || (UM1.DIRT_OMO_2CHAKU + UM1.DIRT_FURYO_2CHAKU) ||
    ' - ' || (UM1.DIRT_OMO_3CHAKU + UM1.DIRT_FURYO_3CHAKU) ||
    ' - ' || (UM1.DIRT_OMO_4CHAKU + UM1.DIRT_FURYO_4CHAKU + 
	UM1.DIRT_OMO_5CHAKU + UM1.DIRT_FURYO_5CHAKU +
	UM1.DIRT_OMO_CHAKUGAI + UM1.DIRT_FURYO_CHAKUGAI)
    AS DIRT_OMO_FURYO
    , (HS.TORIHIKI_KAKAKU / 10000) || '万円' AS SHIJO_TRIHIKI_KAKAKU
    , '生産地 ' || UM.SANCHIMEI AS SEISANCHI
    , '毛色 ' || MC.CONTENT AS MOSHOKU
    , '収得賞金 ' || ((UM1.HEICHI_SHUTOKUSHOKIN_RUIKEI + UM1.SHOGAI_SHUTOKUSHOKIN_RUIKEI) / 100) ||
    '万円' AS SHUTOKUSHOKIN
FROM
    JVD_UMAGOTO_RACE_JOHO SE
    LEFT OUTER JOIN JVD_KEIBAJO_CODE KC
    ON KC.CODE = SE.KEIBAJO_CODE
    LEFT OUTER JOIN JVD_RACE_SHOSAI RA
    ON RA.RACE_CODE = SE.RACE_CODE
    LEFT OUTER JOIN JVD_SEIBETSU_CODE SC
    ON SC.CODE = SE.SEIBETSU_CODE
    LEFT OUTER JOIN JVD_KYOSOBA_MASTER UM
    ON UM.KETTO_TOROKU_BANGO = SE.KETTO_TOROKU_BANGO
    LEFT OUTER JOIN JVD_KYOSOBA_SEISEKI UM1
    ON UM1.KETTO_TOROKU_BANGO = SE.KETTO_TOROKU_BANGO
    LEFT OUTER JOIN JVD_KYOSOBA_TORIHIKI_KAKAKU HS
    ON HS.KETTO_TOROKU_BANGO = SE.KETTO_TOROKU_BANGO
    LEFT OUTER JOIN JVD_MOSHOKU_CODE MC
    ON MC.CODE = SE.MOSHOKU_CODE
WHERE 1 = 1
    AND SE.RACE_CODE = '2011062609040411'
    AND SE.KETTO_TOROKU_BANGO = '2006103168'
;